### PR TITLE
Initial push of current_color branch 

### PR DESCRIPTION
**Pull request by asmentko**
This branch is **not** ready for merging.

I have the card for creating a helper method for current_piece. However, when I looked at the issues that were being dealt with, as well as trying to figure out the whole turn-taking thing, it seemed like we might want to call current_color instead. 

To get it started, I just added current_color as a param in the games_controller. 

According to the chess rules, the first move always goes to white, so current_color will need to be initialized as white. The challenge comes in switching current_color from white to black to white to black, etc. each time a piece is moved. I remember earlier on we had a discussion about keeping track of the state of the game. At the time, I was thinking it wasn't important because we weren't going to have to track a game's history. Now, though, it seems like it would be a really good idea because then we could change current_color every time the state of the game changed. @phrygianjack Didn't you outline an idea for tracking game state in Slack? If so, it's lost to history. Any chance you can remember it? (And sorry I didn't get it earlier.)

I also noticed that @jimchicago was using the same variable for his piece capture logic but was relying on current_piece for current_color's value. My thinking is that we wouldn't need current_piece if we had current_color.

### CODE REVIEW

**Comment by asmentko** [comment]
This works now but I'm not sure if it works the way we want it to. I'll need some input from y'all.

First an explanation and then some comments/questions....

Explanation:
I did some looking around into how other people handle turn taking in games and came up with the following:
- I added two instance variables in the game model file:  current_color and resting_color. These initialize to white and black respectively.
- There's now a switch_colors method in the game model that swaps the colors of current_color and resting_color.
- I removed current_color from the game controller params.
- rspec tests for correct initialization of current_color to white and resting_color to black.
- rspec tests for the switch_colors method successfully show that it will switch current_color from white to black and resting_color from black to white

Comments/Questions:
To get the current_color and resting_color to work properly, the initialize_game_colors has to be called. Here's how it currently looks:
```
    def initialize_game_colors(current_color = 'white', resting_color = 'black')
      @current_color = current_color
      @resting_color = resting_color
    end
```
Since this isn't just a simple initialize method (which screwed up the rest of the game.rb file when I tried creating it like that), it will need to called whenever we start a new game and when you run an rspec test. As an example, here's my rspec tests that shows the initialize_game_colors being called:
```
RSpec.describe Game, type: :model do
  describe 'switch_colors' do
    it 'will switch current_color from white to black' do
      game = FactoryGirl.create(:game)
      game.initialize_game_colors
      game.switch_colors
      expect(game.current_color).to eq('black')
    end
    it 'will switch resting_color from black to white' do
      game = FactoryGirl.create(:game)
      game.initialize_game_colors
      game.switch_colors
      expect(game.resting_color).to eq('white')
    end
  end
end
```

Now for the bigger question:  Is this going to give us the functionality we need for the rest of the methods like capture logic?

**Comment by asmentko** [comment]
Also, do we or do we not need a current_piece method now?

**Comment by erikyoung** [comment]
I think current_piece and current_color were essentially doing the same thing. I also think it's inherent that we call it current_color. I know with the pawn logic, we would have to specify if color = "white" and/or color = "black" in some instances, so this woudl really clear up the color factor.

**Comment by asmentko** [comment]
Erik: I don't think we'll need to specify it's white or black because of the switch_colors method that will be called after every move. Thus, from the start, current_color is white and resting_color is black. After a successful move, the switch_colors method will be called and it will be the opposite.

**Comment by erikyoung** [comment]
Andrew: This will definitely be something to consider with the pawn piece because as we have it set up right now, "white" will only move on direction and "black" will only move another direction. Something to discuss for tomorrow?

**Comment by asmentko** [comment]
Yes, a conversation tomorrow about this would be good. I didn't understand what you were getting at earlier about keeping track of black and white and why that's important to the direction of pawns. Now I do. However, this addition shouldn't conflict because it will still be possible to create if statement like these:  `if Piece.color == 'white'` or `if Piece.current_color == 'white'`

**Comment by phrygianjack** [comment]
`current_color` and `resting_color` exist solely to track whose turn it is, correct? Agreed, let's discuss tomorrow, I feel like we have some integration of various bits to do.

**Comment by asmentko** [comment]
Not solely. The original problem we were trying to solve was to be able to identify current piece, which we wanted to use to tell if another piece was was an enemy or not (i.e. `current_piece.color`). This allows us to do it backwards (i.e., `Piece.current_color`), while also keeping track of turns.

**Comment by asmentko** [comment]
Oh crap. I accidently closed this. Trying to figure how to unclose.

**Comment by phrygianjack** [comment]
Ah, I see - so it not only covers whose turn it is, but aids in determining if a piece belongs to an opponent for capturing logic. I wonder how this relates back to the front-end and HTTP request params (as that's what I've been thinking about for the past day or two). It may be tightly related, or may not really have much of a relation at all.

**Pull request merged**
