### PR TITLE
Controller Move Logic 

### PR DESCRIPTION
**Pull request by phrygianjack**
This method will receive the action from the front-end and flow it down to the move validation methods in the models.

### CODE REVIEW

**Comment by phrygianjack** [comment]
OK so I have a few questions about how this will work.
1. The Rails scaffold created a ton of methods in the controller, some of which I'd have to do some refreshing on to figure out what they do. Mainly, I'm concerned with the `update` method, which I think we could use to update the position of the piece in the database. `respond_to` simply lets Rails send back the ack in whatever format the client requests it (i.e., HTML, JSON, XML). 

2. Trying to figure out how to do `current_piece`. We did a `current_lesson` in Flixter by finding the ID, but in this case I'm not sure if we are finding by ID or finding by a set of parameters, which will yield an ID. I think it's the latter, not sure how to implement that.

3. In thinking about this, I believe we need to also have a `current_game` method, probably in the `games_controller`. This is because we'll eventually need to support multiple concurrent games. For now, we don't need this, so I wrote a card for it on Trello and put it further down the to-do pile. 


Any thoughts would be much appreciated!

**Comment by asmentko** [comment]
Jack,

Update: I am currently reviewing the Javascript Deep Dive tutorial where we made the ToDo app. If you look at step 10, it shows how to set up the update method in the controller and how to create an rspec test for updating. http://www.thefirehoseproject.com/spa/10

Current Piece: I think you're on the right track... but I think you're first suggestion would be the way to go (`Current_Piece = Piece.find(params[:id])`)... which is just an adaptation of what we did in step 10 of the Javascript Deep Dive tutorial.

--Andrew

**Comment by phrygianjack** [comment]
Hmm, thanks, that helps - I think that what I've been thinking of as `move` is really the same as `update`, i.e., if a player wants to move a piece, and the move passes all the rules that we've set up, the piece will be `updated` in the database. So what I really want to do is something along the lines of

```
def move_piece(to_x:, to_y:)
    if piece.valid_move(to_x:, to_y:)
        piece.update(position_x: to_x, position_y: to_y)
    else
        return 'bad move, yo'
    end
end
```
I guess what I'm not quite getting (and this might require thinking a little further along the process train), is how exactly is this `move_piece` method getting triggered?  Is this the right place to put is? I've peeked at a couple other teams' chess code and they didn't have a `move` method, but that doesn't mean we can't do it if it makes sense to us.

**Comment by asmentko** [comment]
That makes sense. As for how it gets triggered... that's where we'll need to use jQuery to extract HTML elements, a process that is still rather mysterious to me. If you look in the next step (11) of the ToDo app, it walks us through the process: http://www.thefirehoseproject.com/spa/11

**Comment by phrygianjack** [comment]
Oy. From reading that, it sounds like the way that the "move" is initiated is by an HTTP `put` request to our Rails server. That means that we need to have the routes set up so that the right method gets triggered. In the ToDo app, they trigger the `update` method directly from the UI. 

If you go into our app currently and run `rake routes`, I see that we've already got a bunch of routes set up, which were auto-generated from when we built those Scaffolds way back when. So the infrastructure is there to have the UI update the coordinates of a piece... kind of. I think.

I kinda get it, but it's going to take some hammering to figure it out perfectly!

I don't want this card to grow legs and run away, so I'm just going to stick to writing the `move_piece` method with the assumption that we'll figure out how to hook it up to the frontend later.

**Comment by phrygianjack** [comment]
Also reading through this lesson, where we re-ordered the lessons using jQuery... might be helpful.

http://www.thefirehoseproject.com/flixter/31

**Comment by phrygianjack** [comment]
So here's the flow as I currently understand it:
- User drags and drops a piece on the GUI
- When the piece "lands", the JavaScript stuff will initiate a `put` request to the app controller `update` method (action)
- The `update` action needs to verify that the move is valid before it succeeds

I think that I need to figure out how to get the `update` action to trigger a move validation logic in the model, but that could be a separate card. First thing is to get the move validation to tie all the validations together:
- Obstructed vertically (may be overridden by capture)
- Obstructed horizontally (may be overridden by capture)
- Obstructed diagonally (may be overriden by capture)
- Destination is on the board
- Move follows the rules of the piece being moved

**Comment by phrygianjack** [comment]
The current branch as of `6504d38` has a successfully operating `move(to_x:, to_y:)` method that basically checks if a move breaks any of the rules we've got in place (obstruction, on-board, or individual piece rules). The next step is getting the controller to run this method before triggering the `#update` action... any ideas?

**Comment by asmentko** [comment]
@phrygianjack What you have so far looks good. However, I'm not sure how to answer your question about the next step for the controller... it's one of those things I would just have to do through trial and error. Do you want to set up a pair programming time?

**Comment by phrygianjack** [comment]
I think the thing that this other team figured out that I was struggling with is this: when you "drop" the piece from the UI, the JavaScript program sends an HTTP 'PUT' request to our app's controller. The new piece coordinates are the `x_position` and `y_position` encapsulated in this request (the `params`). They have not been stored in the database yet, so they are essentially the `to_x` and `to_y` that we've been looking for. That's why in the controller, the other team set `to_x = params[:x_position]`... it pulls the destination from the parameters sent to the controller in the HTTP update request.

**Comment by phrygianjack** [comment]
Need to add tests to ensure that after the update happens, the piece has moved in the database

**Comment by phrygianjack** [comment]
I think it might be helpful to revise the tests on this branch; the controller action and move validations work but some more test coverage would be reassuring.

**Comment by phrygianjack** [comment]
Need to include the capture method in the move tests

**Pull request merged**
